############ EMBEDDING PIPELINE ############
embedding_model_name: "OrdalieTech/Solon-embeddings-large-0.1"
chunk_size: 450
chunk_overlap: 80
separators: ["\n\n", "\n"]
pdf_paths: ["data/01_raw/CG_habitation_RP_protectrice.pdf"]
pdf_metadata_map:
  uuid.pdf: "original_filename.pdf"

############ CLASSIC RAG PIPELINE ############
top_k_retriever: 1
retriever_config:
  search_type: "similarity"
  search_kwargs:
    k: 1

suspicious_patterns: [
    # English
    r"(ignore\s+previous\s+instructions?)",
    r"(###\s*system\s*message\s*###)",
    r"(prompt\s*injection)",
    r"(jailbreak)",
    r"(do\s+anything\s+now)",
    r"(bypass\s+restrictions)",
    r"(override\s+instructions)",

    # Français
    r"(ignorer\s+les\s+instructions\s+précédentes?)",
    r"(###\s*message\s*système\s*###)",
    r"(injection\s*de\s*prompt)",
    r"(jailbreak)",
    r"(faire\s+n'importe\s+quoi\s+maintenant)",
    r"(contourner\s+les\s+restrictions)",
    r"(outrepasser\s+les\s+instructions)",
  ]
